artifact_uri: file:///C:/Users/yash2/OneDrive/Desktop/MLOps/MLOps_Project_2/temp_mlruns/682092487170586959/7fb0dfba0eaf400ab2044ad68c19df25/artifacts
end_time: 1772716836531
entry_point_name: ''
experiment_id: '682092487170586959'
lifecycle_stage: active
run_id: 7fb0dfba0eaf400ab2044ad68c19df25
run_name: welcoming-deer-57
source_name: ''
source_type: 4
source_version: ''
start_time: 1772716836478
status: 4
tags: []
user_id: yash2
